[package]
name = "client"
version = "0.1.0"
authors = ["Casey Primozic <me@ameo.link>"]

[dependencies]
minutiae = { path = "../minutiae", features = ["serde"] }
minutiae-libremote = { path = "../libremote" }
uuid = { version = "0.5.0", features = ["v4"] }
clippy = {version = "*", optional = true}
serde = "1.*.*"
serde_derive = "1.*.*"

[features]
hybrid = []
fat = []
