version: 2

jobs:
  build_test_minutiae:
    docker:
      - image: ubuntu:latest
    steps:
      - checkout
      - run: apt-get update
      - run: apt-get install curl file build-essential pkg-config libssl-dev -y
      - restore_cache:
          key: v2-cargo-nightly-2017-01-30-{{ arch }}
          paths:
            - ~/.cargo
      - run: |
          test -f ~/.cargo/bin/cargo || (curl https://sh.rustup.rs -s > /home/install.sh &&
          chmod +x /home/install.sh &&
          sh /home/install.sh -y --verbose --default-toolchain nightly-2018-01-30)
      - save_cache:
          key: v2-cargo-nightly-2017-01-30-{{ arch }}
          paths:
            - ~/.cargo
      - restore_cache:
          key: v1-minutiae-test-{{ arch }}-{{ checksum "minutiae/Cargo.lock" }}
          paths:
            - ~/project/minutiae/target/
      - run: |
          ~/.cargo/bin/rustup default nightly-2018-01-30 && \
          cd minutiae && \
          ~/.cargo/bin/cargo test --no-fail-fast -- --nocapture
      - run: |
          if [ $CIRCLE_BRANCH = "master" ]
          then
            ~/.cargo/bin/cargo login $CARGO_API_TOKEN
            cd minutiae && ~/.cargo/bin/cargo publish
          fi
      - save_cache:
          key: v1-minutiae-test-{{ arch }}-{{ checksum "minutiae/Cargo.lock" }}
          paths:
            - ~/project/minutiae/target/

  test_client:
    docker:
      - image: ubuntu:latest
    steps:
      - checkout
      - run: apt-get update
      - run: apt-get install curl file build-essential pkg-config libssl-dev -y
      - restore_cache:
          key: v2-cargo-nightly-2017-01-30-{{ arch }}
          paths:
            - ~/.cargo
      - run: |
          test -f ~/.cargo/bin/cargo || (curl https://sh.rustup.rs -s > /home/install.sh &&
          chmod +x /home/install.sh &&
          sh /home/install.sh -y --verbose --default-toolchain nightly-2018-01-30)
      - save_cache:
          key: v2-cargo-nightly-2017-01-30-{{ arch }}
          paths:
            - ~/.cargo
      - restore_cache:
          key: v1-minutiae_client-test-{{ arch }}-{{ checksum "client/Cargo.lock" }}
          paths:
            - ~/project/client/target/
      - run: |
          ~/.cargo/bin/rustup default nightly-2018-01-30 && \
          cd client && \
          ~/.cargo/bin/cargo test --no-fail-fast -- --nocapture
      - save_cache:
          key: v1-minutiae_client-test-{{ arch }}-{{ checksum "client/Cargo.lock" }}
          paths:
            - ~/project/client/target/

  # build_colony:
  #   docker:
  #     - image: docker:17.12.0-ce
  #   steps:
  #     - checkout
  #     - setup_remote_docker

workflows:
  version: 2
  build_and_test:
    jobs:
      - build_test_minutiae
      - test_client
      # - build_colony:
      #   filters:
      #     branches:
      #       only:
      #         - master
