[package]
name = "minutiae"
version = "0.3.0"
authors = ["Casey Primozic <me@ameo.link>"]
description = "Cellular Automata-esque simulation engine involving a 2D universe populated by cells and entities"
repository = "https://github.com/Ameobea/minutiae"
homepage = "https://github.com/Ameobea/minutiae"
keywords = ["simulation", "automata", "engine", "entity"]
license = "MIT"

[dependencies]
num_cpus = "1.4.0"
uuid = { version = "0.5.0", features = ["v4", "serde"] }
serde = { version = "1.*.*", optional = true }
serde_derive = "1.*.*"

[profile.release]
debug = true
lto = true
