[package]
authors = ["Casey Primozic <me@ameo.link>"]
name = "colony"
version = "0.1.0"

[dependencies]
serde = "1.0.27"
serde_derive = "1.0.27"

[dependencies.minutiae]
features = ["server"]
path = "../minutiae"
version = "0.10.0"
