[package]
name = "minutae-fish"
version = "0.1.0"
authors = ["Casey Primozic <me@ameo.link>"]

[dependencies]
minutae = "0.2.1"

pcg = { git = "https://github.com/codahale/pcg.git" }
rand = "0.3"
uuid = { version = "0.5.0", features = ["v4"] }

[profile.release]
debug = true
lto = true
